const AMERICAN_PARENT_COMPANIES = {
  // PepsiCo brands
  doritos: "pepsico",
  lays: "pepsico",
  fritos: "pepsico",
  cheetos: "pepsico",
  tostitos: "pepsico",
  ruffles: "pepsico",
  quaker: "pepsico",
  gatorade: "pepsico",
  pepsi: "pepsico",
  "mountain-dew": "pepsico",
  tropicana: "pepsico",
  aquafina: "pepsico",
  sierra_mist: "pepsico",
  naked: "pepsico",
  bubly: "pepsico",
  muscle_milk: "pepsico",
  rockstar: "pepsico",
  starbucks_frappuccino: "pepsico",
  sabra: "pepsico",
  "cap'n-crunch": "pepsico",
  sunchips: "pepsico",
  "miss-vickies": "pepsico",
  smartfood: "pepsico",
  "rice-a-roni": "pepsico",
  "aunt-jemima": "pepsico",
  "life-cereal": "pepsico",
  "near-east": "pepsico",
  "stacy's-pita-chips": "pepsico",
  "mothers-cookies": "pepsico",
  "cracker-jack": "pepsico",
  "mug-root-beer": "pepsico",
  "brisk": "pepsico",
  "lipton-ready-to-drink": "pepsico",
  "propel": "pepsico",
  "amp-energy": "pepsico",
  "kevita": "pepsico",
  "izze": "pepsico",
  "dole": "pepsico",
  "o.n.e": "pepsico",
  "pasta-roni": "pepsico",
  "funyuns": "pepsico",
  "grandma's-cookies": "pepsico",
  "munchies": "pepsico",
  "sabritones": "pepsico",
  "santitas": "pepsico",
  "spitz": "pepsico",

  // Coca-Cola brands
  "coca-cola": "coca-cola",
  sprite: "coca-cola",
  fanta: "coca-cola",
  "minute-maid": "coca-cola",
  powerade: "coca-cola",
  dasani: "coca-cola",
  vitaminwater: "coca-cola",
  smartwater: "coca-cola",
  gold_peak: "coca-cola",
  simply: "coca-cola",
  fuse: "coca-cola",
  fairlife: "coca-cola",
  honest_tea: "coca-cola",
  innocent_smoothies: "coca-cola",
  topo_chico: "coca-cola",
  "dr-pepper": "coca-cola",
  "canada-dry": "coca-cola",
  schweppes: "coca-cola",
  "a&w": "coca-cola",
  "barqs": "coca-cola",
  "costa-coffee": "coca-cola",
  "peace-tea": "coca-cola",
  "fresca": "coca-cola",
  "seagrams": "coca-cola",
  "mello-yello": "coca-cola",
  "northern-neck": "coca-cola",
  "pibb-xtra": "coca-cola",
  "full-throttle": "coca-cola",
  "tab": "coca-cola",
  "odwalla": "coca-cola",
  "zico": "coca-cola",
  "core-power": "coca-cola",
  "bodyarmor": "coca-cola",
  "dunkin-bottled": "coca-cola",
  "monster": "coca-cola",
  "nos-energy": "coca-cola",
  "glaceau": "coca-cola",
  "fuze-tea": "coca-cola",
  "hi-c": "coca-cola",
  "surge": "coca-cola",

  // Mondelez brands
  oreo: "mondelez",
  ritz: "mondelez",
  "chips-ahoy": "mondelez",
  trident: "mondelez",
  cadbury: "mondelez",
  toblerone: "mondelez",
  halls: "mondelez",
  philadelphia: "mondelez",
  milka: "mondelez",
  belvita: "mondelez",
  wheat_thins: "mondelez",
  honey_maids: "mondelez",
  dentyne: "mondelez",
  clorets: "mondelez",
  "sour-patch-kids": "mondelez",
  "swedish-fish": "mondelez",
  "triscuit": "mondelez",
  "tang": "mondelez",
  "newtons": "mondelez",
  "nutter-butter": "mondelez",
  "good-thins": "mondelez",
  "perfect-snacks": "mondelez",
  "tate's-bake-shop": "mondelez",
  "green-black's": "mondelez",
  "lu-cookies": "mondelez",
  "nabisco": "mondelez",
  "premium-crackers": "mondelez",
  "royal-baking-powder": "mondelez",
  "stride": "mondelez",
  "bubbaloo": "mondelez",
  "chiclets": "mondelez",
  "cls": "mondelez",
  "dirol": "mondelez",
  "freshen-up": "mondelez",
  "stimorol": "mondelez",
  "trebor": "mondelez",
  "maynards": "mondelez",
  "bassetts": "mondelez",
  "freia": "mondelez",
  "lacta": "mondelez",
  "marabou": "mondelez",
  "terry's": "mondelez",
  "cote-d'or": "mondelez",

  // Kraft Heinz brands
  kraft: "kraft-heinz",
  heinz: "kraft-heinz",
  "oscar-mayer": "kraft-heinz",
  planters: "kraft-heinz",
  "jell-o": "kraft-heinz",
  "maxwell-house": "kraft-heinz",
  "capri-sun": "kraft-heinz",
  grey_poupon: "kraft-heinz",
  kool_aid: "kraft-heinz",
  velveeta: "kraft-heinz",
  "lunchables": "kraft-heinz",
  "classico": "kraft-heinz",
  "boca-burger": "kraft-heinz",
  "philadelphia-cream-cheese": "kraft-heinz",
  "crystal-light": "kraft-heinz",
  "stove-top": "kraft-heinz",
  "bagel-bites": "kraft-heinz",
  "ore-ida": "kraft-heinz",
  "taco-bell-at-home": "kraft-heinz",
  "kraft-dinner": "kraft-heinz",
  "shake-n-bake": "kraft-heinz",
  "cool-whip": "kraft-heinz",
  "miracle-whip": "kraft-heinz",
  "kraft-singles": "kraft-heinz",
  "kraft-mac-cheese": "kraft-heinz",
  "kraft-mayo": "kraft-heinz",
  "kraft-bbq-sauce": "kraft-heinz",
  "kraft-dressing": "kraft-heinz",
  "plasmon": "kraft-heinz",
  "delimex": "kraft-heinz",
  "gevalia": "kraft-heinz",
  "golden-circle": "kraft-heinz",
  "hp-sauce": "kraft-heinz",
  "lea-perrins": "kraft-heinz",
  "master-soy-sauce": "kraft-heinz",
  "pudliszki": "kraft-heinz",
  "quero": "kraft-heinz",
  "wattie's": "kraft-heinz",
  "weight-watchers": "kraft-heinz",

  // Kellogg brands (expanded)
  kelloggs: "kellogg",
  pringles: "kellogg",
  "cheez-it": "kellogg",
  eggo: "kellogg",
  "nutri-grain": "kellogg",
  "pop-tarts": "kellogg",
  "rice-krispies": "kellogg",
  "special-k": "kellogg",
  "frosted-flakes": "kellogg",
  "corn-flakes": "kellogg",
  "raisin-bran": "kellogg",
  "apple-jacks": "kellogg",
  "froot-loops": "kellogg",
  "mini-wheats": "kellogg",
  "morningstar-farms": "kellogg",
  "kashi": "kellogg",
  "bear-naked": "kellogg",
  "corn-pops": "kellogg",
  "crispix": "kellogg",
  "smart-start": "kellogg",
  "all-bran": "kellogg",
  "cracklin-oat-bran": "kellogg",
  "mueslix": "kellogg",
  "smorz": "kellogg",
  "town-house": "kellogg",
  "zesta": "kellogg",
  "rxbar": "kellogg",
  "incogmeato": "kellogg",
  "pure-organic": "kellogg",
  "happy-inside": "kellogg",
  "joybol": "kellogg",
  "vector": "kellogg",
  "jumbo-snax": "kellogg",
  "murray": "kellogg",
  "austin": "kellogg",
  "sunshine": "kellogg",
  "carr's": "kellogg",
  "club": "kellogg",
  "toasteds": "kellogg",
  "right-bites": "kellogg",

  // General Mills brands (expanded)
  "general-mills": "general-mills",
  "betty-crocker": "general-mills",
  pillsbury: "general-mills",
  cheerios: "general-mills",
  "nature-valley": "general-mills",
  yoplait: "general-mills",
  "haagen-dazs": "general-mills",
  annie: "general-mills",
  lucky_charms: "general-mills",
  cocoa_puffs: "general-mills",
  wheaties: "general-mills",
  "trix": "general-mills",
  "chex": "general-mills",
  "cinnamon-toast-crunch": "general-mills",
  "green-giant": "general-mills",
  "old-el-paso": "general-mills",
  "totinos": "general-mills",
  "progresso": "general-mills",
  "fiber-one": "general-mills",
  "bugles": "general-mills",
  "cascadian-farm": "general-mills",
  "larabar": "general-mills",
  "annie's-homegrown": "general-mills",
  "blue-buffalo": "general-mills",
  "muir-glen": "general-mills",
  "food-should-taste-good": "general-mills",
  "epic-provisions": "general-mills",
  "gardetto's": "general-mills",
  "golden-grahams": "general-mills",
  "kix": "general-mills",
  "monster-cereals": "general-mills",
  "oatmeal-crisp": "general-mills",
  "reese's-puffs": "general-mills",
  "total": "general-mills",
  "hamburger-helper": "general-mills",
  "suddenly-salad": "general-mills",
  "fruit-roll-ups": "general-mills",
  "fruit-by-the-foot": "general-mills",
  "gushers": "general-mills",
  "dunkaroos": "general-mills",

  // Mars brands (expanded)
  mars: "mars",
  mms: "mars",
  snickers: "mars",
  twix: "mars",
  "milky-way": "mars",
  skittles: "mars",
  "uncle-bens": "mars",
  pedigree: "mars",
  whiskas: "mars",
  orbit: "mars",
  starburst: "mars",
  five_gum: "mars",
  "3-musketeers": "mars",
  "dove-chocolate": "mars",
  "altoids": "mars",
  "life-savers": "mars",
  "royal-canin": "mars",
  "extra-gum": "mars",
  "cesar": "mars",
  "bounty-chocolate": "mars",
  "maltesers": "mars",
  "galaxy-chocolate": "mars",
  "hubba-bubba": "mars",
  "combos": "mars",
  "ethel-m-chocolates": "mars",
  "goodrx": "mars",
  "iams": "mars",
  "nutro": "mars",
  "sheba": "mars",
  "temptations": "mars",
  "greenies": "mars",
  "dreamies": "mars",
  "eukanuba": "mars",
  "perfect-fit": "mars",
  "chappi": "mars",
  "catsan": "mars",
  "crave": "mars",
  "dentastix": "mars",
  "schmackos": "mars",
  "trill": "mars",

  // Unilever brands (expanded)
  dove: "unilever",
  axe: "unilever",
  "ben-jerrys": "unilever",
  breyers: "unilever",
  degree: "unilever",
  hellmanns: "unilever",
  knorr: "unilever",
  lipton: "unilever",
  vaseline: "unilever",
  tresemme: "unilever",
  surf: "unilever",
  suave: "unilever",
  ponds: "unilever",
  "st-ives": "unilever",
  "simple-skincare": "unilever",
  "seventh-generation": "unilever",
  "love-beauty-planet": "unilever",
  "talenti": "unilever",
  "klondike": "unilever",
  "good-humor": "unilever",
  "magnum-ice-cream": "unilever",
  "popsicle": "unilever",
  "ragu": "unilever",
  "bertolli": "unilever",
  "country-crock": "unilever",
  "imperial-margarine": "unilever",
  "promise": "unilever",
  "slim-fast": "unilever",
  "caress": "unilever",
  "nexxus": "unilever",
  "noxzema": "unilever",
  "q-tips": "unilever",
  "vim": "unilever",
  "pure-leaf": "unilever",
  "tazo": "unilever",
  "maille": "unilever",
  "maizena": "unilever",
  "skippy": "unilever",
  "wish-bone": "unilever",

  // Procter & Gamble brands (expanded)
  tide: "p&g",
  pampers: "p&g",
  gillette: "p&g",
  pantene: "p&g",
  "head-shoulders": "p&g",
  "oral-b": "p&g",
  crest: "p&g",
  dawn: "p&g",
  febreze: "p&g",
  charmin: "p&g",
  bounty: "p&g",
  always: "p&g",
  olay: "p&g",
  braun: "p&g",
  "old-spice": "p&g",
  "swiffer": "p&g",
  "tampax": "p&g",
  "vicks": "p&g",
  "downy": "p&g",
  "gain": "p&g",
  "metamucil": "p&g",
  "pepto-bismol": "p&g",
  "prilosec": "p&g",
  "scope": "p&g",
  "aussie": "p&g",
  "herbal-essences": "p&g",
  "ivory": "p&g",
  "joy": "p&g",
  "safeguard": "p&g",
  "zzzquil": "p&g",
  "align": "p&g",
  "bounce": "p&g",
  "cascade": "p&g",
  "comet": "p&g",
  "dreft": "p&g",
  "fixodent": "p&g",
  "mr-clean": "p&g",
  "puffs": "p&g",
  "secret": "p&g",

  // Johnson & Johnson brands (expanded)
  johnson: "j&j",
  "band-aid": "j&j",
  neutrogena: "j&j",
  tylenol: "j&j",
  listerine: "j&j",
  "clean-clear": "j&j",
  aveeno: "j&j",
  zyrtec: "j&j",
  "benadryl": "j&j",
  "motrin": "j&j",
  "stayfree": "j&j",
  "rogaine": "j&j",
  "visine": "j&j",
  "nicorette": "j&j",
  "pepcid": "j&j",
  "sudafed": "j&j",
  "acuvue": "j&j",
  "bengay": "j&j",
  "carefree": "j&j",
  "cortaid": "j&j",
  "desitin": "j&j",
  "imodium": "j&j",
  "johnson-baby": "j&j",
  "lactaid": "j&j",
  "lubriderm": "j&j",
  "neosporin": "j&j",
  "ob": "j&j",
  "penaten": "j&j",
  "rhinocort": "j&j",
  "roc": "j&j",
  "sinutab": "j&j",
  "splenda": "j&j",
  "nizoral": "j&j",

  // Colgate-Palmolive brands (expanded)
  colgate: "colgate-palmolive",
  palmolive: "colgate-palmolive",
  "speed-stick": "colgate-palmolive",
  "irish-spring": "colgate-palmolive",
  softsoap: "colgate-palmolive",
  "ajax": "colgate-palmolive",
  "murphy-oil-soap": "colgate-palmolive",
  "science-diet": "colgate-palmolive",
  "tom's-of-maine": "colgate-palmolive",
  "fabuloso": "colgate-palmolive",
  "meridol": "colgate-palmolive",
  "sanex": "colgate-palmolive",
  "tahiti": "colgate-palmolive",
  "tender-care": "colgate-palmolive",
  "protex": "colgate-palmolive",
  "filorga": "colgate-palmolive",
  "elta-md": "colgate-palmolive",
  "pca-skin": "colgate-palmolive",
  "hill's-pet": "colgate-palmolive",
  "suavitel": "colgate-palmolive",

  // Campbell Soup Company brands (expanded)
  campbells: "campbell",
  "pepperidge-farm": "campbell",
  swanson: "campbell",
  prego: "campbell",
  v8: "campbell",
  pace: "campbell",
  "goldfish": "campbell",
  "royal-dansk": "campbell",
  "snyder's-of-hanover": "campbell",
  "lance": "campbell",
  "kettle-brand": "campbell",
  "emerald-nuts": "campbell",
  "late-july": "campbell",
  "plum-organics": "campbell",
  "pacific-foods": "campbell",
  "garden-fresh": "campbell",
  "bolthouse-farms": "campbell",
  "arnott's": "campbell",
  "tim-tam": "campbell",
  "shapes": "campbell",
  "milano": "campbell",
  "farmhouse": "campbell",
  "cape-cod": "campbell",
  "pretzel-crisps": "campbell",
  "archway": "campbell",
  "spartanburg": "campbell",

  // Hershey brands (expanded)
  hersheys: "hershey",
  reeses: "hershey",
  kisses: "hershey",
  "kit-kat": "hershey",
  brookside: "hershey",
  whoppers: "hershey",
  twizzlers: "hershey",
  "york": "hershey",
  "almond-joy": "hershey",
  "mounds": "hershey",
  "jolly-rancher": "hershey",
  "ice-breakers": "hershey",
  "heath": "hershey",
  "milk-duds": "hershey",
  "5th-avenue": "hershey",
  "zero-bar": "hershey",
  "good-n-plenty": "hershey",
  "breath-savers": "hershey",
  "symphony": "hershey",
  "zagnut": "hershey",
  "mr-goodbar": "hershey",
  "payday": "hershey",
  "skor": "hershey",
  "sofit": "hershey",
  "dagoba": "hershey",
  "lily's": "hershey",

  // ConAgra brands (expanded)
  conagra: "conagra",
  "healthy-choice": "conagra",
  "slim-jim": "conagra",
  "orville-redenbachers": "conagra",
  hunts: "conagra",
  "chef-boyardee": "conagra",
  "pinnacle-foods": "conagra",
  "earth-balance": "conagra",
  "pam": "conagra",
  "vlasic": "conagra",
  "birds-eye": "conagra",
  "duncan-hines": "conagra",
  "mrs-butterworths": "conagra",
  "swiss-miss": "conagra",
  "peter-pan": "conagra",
  "act-ii": "conagra",
  "angie's-boomchickapop": "conagra",
  "banquet": "conagra",
  "bertolli-frozen": "conagra",
  "big-mama": "conagra",
  "blake's": "conagra",
  "blue-bonnet": "conagra",
  "david": "conagra",
  "egg-beaters": "conagra",
  "fiddle-faddle": "conagra",
  "gardein": "conagra",
  "jiffy-pop": "conagra",
  "la-choy": "conagra",
  "libby's": "conagra",
  "manwich": "conagra",
  "marie-callender's": "conagra",
  "parkay": "conagra",
  "penrose": "conagra",
  "poppycock": "conagra",
  "reddi-wip": "conagra",
  "ro*tel": "conagra",
  "snack-pack": "conagra",
  "van-camp's": "conagra",
  "wesson": "conagra",
  "wolf": "conagra",

  // Post Holdings brands (expanded)
  post: "post",
  "honey-bunches": "post",
  "grape-nuts": "post",
  hostess: "post",
  powerbar: "post",
  dymatize: "post",
  "premier-protein": "post",
  "malt-o-meal": "post",
  "better-oats": "post",
  "golden-crisp": "post",
  "pebbles": "post",
  "8th-continent": "post",
  "attune-foods": "post",
  "barbara's": "post",
  "crystal-wheat": "post",
  "good-mornings": "post",
  "great-grains": "post",
  "michael-foods": "post",
  "mom's-best": "post",
  "peace-cereal": "post",
  "weetabix": "post",
  "alpen": "post",
  "ready-brek": "post",
  "bob-evans": "post",
  "country-club": "post",
  "farm-rich": "post",
  "PHE": "post",
  "supreme-protein": "post",

  // Clorox brands (expanded)
  clorox: "clorox",
  "pine-sol": "clorox",
  "liquid-plumr": "clorox",
  brita: "clorox",
  glad: "clorox",
  "hidden-valley": "clorox",
  burt_bees: "clorox",
  "green-works": "clorox",
  "fresh-step": "clorox",
  "kingsford": "clorox",
  "burt's-bees": "clorox",
  "formula-409": "clorox",
  "armor-all": "clorox",
  "tilex": "clorox",
  "ever-clean": "clorox",
  "scoop-away": "clorox",
  "s.o.s": "clorox",
  "clorox-healthcare": "clorox",
  "dispatch": "clorox",
  "clorox-pro": "clorox",
  "caltech": "clorox",
  "aplicare": "clorox",
  "sonoma-sparkler": "clorox",
  "kitchen-bouquet": "clorox",
  "kc-masterpiece": "clorox",

  // Tyson Foods brands (expanded)
  tyson: "tyson",
  "jimmy-dean": "tyson",
  "hillshire-farm": "tyson",
  "ball-park": "tyson",
  "state-fair": "tyson",
  "wright": "tyson",
  "aidells": "tyson",
  "gallo-salame": "tyson",
  "sara-lee": "tyson",
  "nature-raised-farms": "tyson",
  "true-chews": "tyson",
  "tastybird": "tyson",
  "bosco's": "tyson",
  "corn-king": "tyson",
  "deli-express": "tyson",
  "mexican-original": "tyson",
  "wright-brand": "tyson",
  "raised-rooted": "tyson",
  "any'tizers": "tyson",
  "bonici": "tyson",

  // Hormel brands (expanded)
  hormel: "hormel",
  spam: "hormel",
  "skippy-pb": "hormel",
  "dinty-moore": "hormel",
  "jennie-o": "hormel",
  "lloyd's": "hormel",
  "house-of-tsang": "hormel",
  "muscle-milk": "hormel",
  "applegate": "hormel",
  "columbus-craft-meats": "hormel",
  "corn-nuts": "hormel",
  "mary-kitchen": "hormel",
  "chi-chi's": "hormel",
  "farmer-john": "hormel",
  "justin's": "hormel",
  "la-victoria": "hormel",
  "wholly-guacamole": "hormel",
  "fontanini": "hormel",
  "bacon-bits": "hormel",

  // McCormick brands (expanded)
  mccormick: "mccormick",
  "old-bay": "mccormick",
  "french's": "mccormick",
  "frank's-red-hot": "mccormick",
  "stubb's": "mccormick",
  "lawry's": "mccormick",
  "zatarain's": "mccormick",
  "thai-kitchen": "mccormick",
  "simply-asia": "mccormick",
  "ducros": "mccormick",
  "schwartz": "mccormick",
  "kamis": "mccormick",
  "gourmet-garden": "mccormick",
  "club-house": "mccormick",
  "vahine": "mccormick",
  "aeroplane": "mccormick",
  "cattlemen's": "mccormick",
  "cholula": "mccormick",
  "el-guapo": "mccormick",
  "keen's": "mccormick",

  // JM Smucker brands (expanded)
  smuckers: "smucker",
  "jif": "smucker",
  "folgers": "smucker",
  "dunkin-coffee": "smucker",
  "pillsbury-baking": "smucker",
  "crisco": "smucker",
  "hungry-jack": "smucker",
  "martha-white": "smucker",
  "cafe-bustelo": "smucker",
  "rachael-ray-nutrish": "smucker",
  "milk-bone": "smucker",
  "meow-mix": "smucker",
  "kibbles-n-bits": "smucker",
  "9lives": "smucker",
  "nature's-recipe": "smucker",
  "robin-hood": "smucker",
  "truvia": "smucker",
  "eagle-brand": "smucker",
  "sahale-snacks": "smucker",
  "pet-milk": "smucker",

  // Nestlé USA brands (expanded)
  "nestle-usa": "nestle-usa",
  "stouffer's": "nestle-usa",
  "lean-cuisine": "nestle-usa",
  "hot-pockets": "nestle-usa",
  "digiorno": "nestle-usa",
  "tombstone": "nestle-usa",
  "california-pizza-kitchen": "nestle-usa",
  "jack's": "nestle-usa",
  "toll-house": "nestle-usa",
  "coffee-mate": "nestle-usa",
  "nesquik": "nestle-usa",
  "nescafe": "nestle-usa",
  "gerber": "nestle-usa",
  "boost": "nestle-usa",
  "carnation": "nestle-usa",
  "sweet-earth": "nestle-usa",
  "buitoni": "nestle-usa",
  "dreyer's": "nestle-usa",
  "edy's": "nestle-usa",
  "outshine": "nestle-usa",
  "skinny-cow": "nestle-usa",
  "drumstick": "nestle-usa",
  "häagen-dazs": "nestle-usa",
  "nestlé-crunch": "nestle-usa",
  "butterfinger": "nestle-usa",
  "baby-ruth": "nestle-usa",
  "wonka": "nestle-usa",
  "nerds": "nestle-usa",
  "laffy-taffy": "nestle-usa",
  "gobstopper": "nestle-usa",
  "sweetarts": "nestle-usa",
  "runts": "nestle-usa",
  "bottle-caps": "nestle-usa",
  "spree": "nestle-usa",

  // Del Monte brands (expanded)
  "del-monte": "del-monte",
  "contadina": "del-monte",
  "s&w": "del-monte",
  "college-inn": "del-monte",
  "fruit-naturals": "del-monte",
  "sunfresh": "del-monte",
  "fruit-burst": "del-monte",
  "nature's-goodness": "del-monte",
  "orchard-select": "del-monte",
  "fruit-refreshers": "del-monte",
  "veggieful": "del-monte",
  "bubble-fruit": "del-monte",
  "fruit-cups": "del-monte",
  "squeezie": "del-monte",
  "fruit-crunch-parfait": "del-monte",
  "deluxe-gold": "del-monte",
  "garden-quality": "del-monte",
  "kitchen-basics": "del-monte",
  "fruit-undressed": "del-monte",
  "fruit-and-chia": "del-monte",

  // Ocean Spray brands (expanded)
  "ocean-spray": "ocean-spray",
  "craisins": "ocean-spray",
  "wave": "ocean-spray",
  "pure-fruit-juice": "ocean-spray",
  "diet-juice": "ocean-spray",
  "light-juice": "ocean-spray",
  "cranberry-juice": "ocean-spray",
  "cranberry-sauce": "ocean-spray",
  "growing-goodness": "ocean-spray",
  "pure-cranberry": "ocean-spray",
  "cranberry-blend": "ocean-spray",
  "cranberry-fruit-drink": "ocean-spray",
  "cranberry-classic": "ocean-spray",
  "cranberry-cocktail": "ocean-spray",
  "cranberry-concentrate": "ocean-spray",

  // Dole Food Company brands (expanded)
  "dole-whip": "dole",
  "dole-packaged-foods": "dole",
  "dole-fresh-vegetables": "dole",
  "dole-fresh-fruits": "dole",
  "dole-frozen": "dole",
  "dole-jarred-fruit": "dole",
  "dole-fruit-bowls": "dole",
  "dole-smoothie-bowls": "dole",
  "dole-juice": "dole",
  "dole-dried-fruits": "dole",
  "sparklers": "dole",
  "fruit-n-gel": "dole",
  "fruit-crisps": "dole",
  "real-fruit-bites": "dole",
  "fruitocracy": "dole",

  // Land O'Lakes brands (expanded)
  "land-o-lakes": "land-o-lakes",
  "alpine-lace": "land-o-lakes",
  "kozy-shack": "land-o-lakes",
  "land-o-lakes-butter": "land-o-lakes",
  "land-o-lakes-cheese": "land-o-lakes",
  "land-o-lakes-milk": "land-o-lakes",
  "land-o-lakes-eggs": "land-o-lakes",
  "land-o-lakes-cocoa": "land-o-lakes",
  "land-o-lakes-margarine": "land-o-lakes",
  "land-o-lakes-half-and-half": "land-o-lakes",
  "land-o-lakes-whipping-cream": "land-o-lakes",
  "land-o-lakes-sour-cream": "land-o-lakes",

  // Bush's Best brands (expanded)
  "bush's": "bush's",
  "bush's-baked-beans": "bush's",
  "bush's-grillin-beans": "bush's",
  "bush's-chili-beans": "bush's",
  "bush's-kidney-beans": "bush's",
  "bush's-black-beans": "bush's",
  "bush's-pinto-beans": "bush's",
  "bush's-great-northern-beans": "bush's",
  "bush's-navy-beans": "bush's",
  "bush's-cannellini-beans": "bush's",
  "bush's-organic-beans": "bush's",
  "bush's-savory-beans": "bush's",
  "bush's-bean-pot": "bush's",
  "bush's-hummus-made-easy": "bush's",

  // Blue Diamond brands (expanded)
  "blue-diamond": "blue-diamond",
  "almond-breeze": "blue-diamond",
  "nut-thins": "blue-diamond",
  "almond-flour": "blue-diamond",
  "almonds-snacks": "blue-diamond",
  "almond-protein-powder": "blue-diamond",
  "crafted-gourmet-almonds": "blue-diamond",
  "nut-chips": "blue-diamond",
  "almond-cooking-oil": "blue-diamond",
  "artisan-nut-thins": "blue-diamond",
  "almond-extract": "blue-diamond",

  // Bob's Red Mill brands (expanded)
  "bobs-red-mill": "bobs-red-mill",
  "organic-flour": "bobs-red-mill",
  "gluten-free-flour": "bobs-red-mill",
  "whole-grain": "bobs-red-mill",
  "granola": "bobs-red-mill",
  "oatmeal": "bobs-red-mill",
  "protein-powder": "bobs-red-mill",
  "baking-mixes": "bobs-red-mill",
  "grains": "bobs-red-mill",
  "beans": "bobs-red-mill",
  "seeds": "bobs-red-mill",
  "nutritional-boosters": "bobs-red-mill",
  "paleo-flour": "bobs-red-mill",
  "muesli": "bobs-red-mill",

  // Annie's Homegrown brands (expanded)
  "annies": "annies",
  "annies-mac-and-cheese": "annies",
  "annies-snacks": "annies",
  "annies-cereal": "annies",
  "annies-frozen": "annies",
  "annies-dressings": "annies",
  "annies-condiments": "annies",
  "annies-fruit-snacks": "annies",
  "annies-crackers": "annies",
  "annies-cookies": "annies",
  "annies-granola-bars": "annies",
  "annies-yogurt": "annies",
  "annies-baking": "annies",
  "annies-pasta": "annies",

  // Amy's Kitchen brands (expanded)
  "amys": "amys",
  "amys-frozen-meals": "amys",
  "amys-soups": "amys",
  "amys-beans": "amys",
  "amys-chili": "amys",
  "amys-pasta-sauce": "amys",
  "amys-salsa": "amys",
  "amys-candy": "amys",
  "amys-pizza": "amys",
  "amys-bowls": "amys",
  "amys-burritos": "amys",
  "amys-veggie-burgers": "amys",
  "amys-snacks": "amys",
  "amys-breakfast": "amys",

  // Kind brands (expanded)
  "kind": "kind",
  "kind-bars": "kind",
  "kind-healthy-grains": "kind",
  "kind-breakfast-bars": "kind",
  "kind-frozen": "kind",
  "kind-protein": "kind",
  "kind-minis": "kind",
  "kind-kids": "kind",
  "kind-clusters": "kind",
  "kind-granola": "kind",
  "kind-snack-mix": "kind",
  "kind-nut-butter-bars": "kind",
  "kind-fruit-bites": "kind",
  "kind-pressed": "kind",

  // Chobani brands (expanded)
  "chobani": "chobani",
  "chobani-greek-yogurt": "chobani",
  "chobani-flip": "chobani",
  "chobani-less-sugar": "chobani",
  "chobani-complete": "chobani",
  "chobani-probiotic": "chobani",
  "chobani-zero-sugar": "chobani",
  "chobani-coffee": "chobani",
  "chobani-creamer": "chobani",
  "chobani-oat": "chobani",
  "chobani-kids": "chobani",
  "chobani-gimmies": "chobani",
  "chobani-drinks": "chobani",
  "chobani-non-dairy": "chobani",

  // Clif Bar brands (expanded)
  "clif": "clif",
  "clif-bar": "clif",
  "luna-bar": "clif",
  "clif-kid": "clif",
  "clif-builders": "clif",
  "clif-bloks": "clif",
  "clif-shot": "clif",
  "clif-whey": "clif",
  "clif-nut-butter": "clif",
  "clif-thins": "clif",
  "clif-granola": "clif",
  "clif-cereal": "clif",
  "clif-protein": "clif",
  "clif-minis": "clif",

  // Stonyfield Farm brands (expanded)
  "stonyfield": "stonyfield",
  "stonyfield-organic": "stonyfield",
  "stonyfield-yogurt": "stonyfield",
  "stonyfield-kids": "stonyfield",
  "stonyfield-smoothies": "stonyfield",
  "stonyfield-greek": "stonyfield",
  "stonyfield-frozen": "stonyfield",
  "stonyfield-milk": "stonyfield",
  "stonyfield-cream": "stonyfield",
  "stonyfield-snacks": "stonyfield",
  "brown-cow": "stonyfield",
  "yo-baby": "stonyfield",
  "yo-kids": "stonyfield",
  "yo-toddler": "stonyfield",

  // Organic Valley brands (expanded)
  "organic-valley": "organic-valley",
  "organic-prairie": "organic-valley",
  "grassmilk": "organic-valley",
  "fuel": "organic-valley",
  "moon-valley": "organic-valley",
  "organic-fuel": "organic-valley",
  "organic-balance": "organic-valley",
  "organic-valley-cheese": "organic-valley",
  "organic-valley-butter": "organic-valley",
  "organic-valley-eggs": "organic-valley",
  "organic-valley-milk": "organic-valley",
  "organic-valley-cream": "organic-valley",
  "organic-valley-half-and-half": "organic-valley",
  "organic-valley-sour-cream": "organic-valley",

  // Justin's brands (expanded)
  "justins": "justins",
  "justins-nut-butter": "justins",
  "justins-peanut-butter": "justins",
  "justins-almond-butter": "justins",
  "justins-cashew-butter": "justins",
  "justins-chocolate": "justins",
  "justins-peanut-butter-cups": "justins",
  "justins-snack-packs": "justins",
  "justins-protein-bars": "justins",
  "justins-squeeze-packs": "justins",

  // Wonderful Company brands (expanded)
  "wonderful": "wonderful",
  "pom-wonderful": "wonderful",
  "wonderful-pistachios": "wonderful",
  "wonderful-almonds": "wonderful",
  "wonderful-halos": "wonderful",
  "wonderful-seedless-lemons": "wonderful",
  "fiji-water": "wonderful",
  "justin-wine": "wonderful",
  "landmark-wines": "wonderful",
  "jnsq-wines": "wonderful",
  "suterra": "wonderful",
  "teleflora": "wonderful",

  // Scharffen Berger brands (expanded)
  "scharffen-berger": "scharffen-berger",
  "scharffen-berger-chocolate": "scharffen-berger",
  "scharffen-berger-cocoa": "scharffen-berger",
  "scharffen-berger-baking": "scharffen-berger",
  "scharffen-berger-gifts": "scharffen-berger",

  // Newman's Own brands (expanded)
  "newmans-own": "newmans-own",
  "newmans-pasta-sauce": "newmans-own",
  "newmans-salad-dressing": "newmans-own",
  "newmans-lemonade": "newmans-own",
  "newmans-salsa": "newmans-own",
  "newmans-cookies": "newmans-own",
  "newmans-pretzels": "newmans-own",
  "newmans-popcorn": "newmans-own",
  "newmans-mints": "newmans-own",
  "newmans-coffee": "newmans-own",
  "newmans-tea": "newmans-own",
  "newmans-wine": "newmans-own",
  "newmans-pet-food": "newmans-own",

  // Cascadian Farm brands (expanded)
  "cascadian-farm-cereal": "cascadian-farm",
  "cascadian-farm-frozen": "cascadian-farm",
  "cascadian-farm-bars": "cascadian-farm",
  "cascadian-farm-snacks": "cascadian-farm",
  "cascadian-farm-juice": "cascadian-farm",
  "cascadian-farm-berries": "cascadian-farm",
  "cascadian-farm-vegetables": "cascadian-farm",
  "cascadian-farm-fruits": "cascadian-farm",

  // Back to Nature brands (expanded)
  "back-to-nature": "back-to-nature",
  "back-to-nature-cookies": "back-to-nature",
  "back-to-nature-crackers": "back-to-nature",
  "back-to-nature-granola": "back-to-nature",
  "back-to-nature-nuts": "back-to-nature",
  "back-to-nature-juice": "back-to-nature",
  "back-to-nature-soup": "back-to-nature",
  "back-to-nature-mac-cheese": "back-to-nature",

  // Applegate Farms brands (expanded)
  "applegate-farms": "applegate",
  "applegate-naturals": "applegate",
  "applegate-organics": "applegate",
  "applegate-hot-dogs": "applegate",
  "applegate-bacon": "applegate",
  "applegate-sausage": "applegate",
  "applegate-deli-meat": "applegate",
  "applegate-chicken": "applegate",
  "applegate-turkey": "applegate",
  "applegate-beef": "applegate",
  "applegate-cheese": "applegate",

  // Earthbound Farm brands (expanded)
  "earthbound-farm": "earthbound-farm",
  "earthbound-organic": "earthbound-farm",
  "earthbound-lettuce": "earthbound-farm",
  "earthbound-greens": "earthbound-farm",
  "earthbound-spinach": "earthbound-farm",
  "earthbound-herbs": "earthbound-farm",
  "earthbound-frozen": "earthbound-farm",
  "earthbound-powermeal": "earthbound-farm",
  "earthbound-snacks": "earthbound-farm",

  // Purely Elizabeth brands (expanded)
  "purely-elizabeth": "purely-elizabeth",
  "purely-granola": "purely-elizabeth",
  "purely-oatmeal": "purely-elizabeth",
  "purely-pancake-mix": "purely-elizabeth",
  "purely-bars": "purely-elizabeth",
  "purely-superfood": "purely-elizabeth",
  "purely-hot-cereal": "purely-elizabeth",
  "purely-grain-free": "purely-elizabeth",
  "purely-protein": "purely-elizabeth",
  "purely-snacks": "purely-elizabeth",

  // Simple Mills brands (expanded)
  "simple-mills": "simple-mills",
  "simple-mills-crackers": "simple-mills",
  "simple-mills-cookies": "simple-mills",
  "simple-mills-baking-mixes": "simple-mills",
  "simple-mills-frosting": "simple-mills",
  "simple-mills-bread-mix": "simple-mills",
  "simple-mills-cake-mix": "simple-mills",
  "simple-mills-pizza-dough": "simple-mills",
  "simple-mills-brownies": "simple-mills",
  "simple-mills-snacks": "simple-mills",

  // Beyond Meat brands (expanded)
  "beyond-meat": "beyond-meat",
  "beyond-burger": "beyond-meat",
  "beyond-beef": "beyond-meat",
  "beyond-sausage": "beyond-meat",
  "beyond-meatballs": "beyond-meat",
  "beyond-breakfast-sausage": "beyond-meat",
  "beyond-ground": "beyond-meat",
  "beyond-chicken": "beyond-meat",
  "beyond-jerky": "beyond-meat",
  "beyond-crumbles": "beyond-meat",

  // Impossible Foods brands (expanded)
  "impossible-foods": "impossible-foods",
  "impossible-burger": "impossible-foods",
  "impossible-sausage": "impossible-foods",
  "impossible-pork": "impossible-foods",
  "impossible-chicken": "impossible-foods",
  "impossible-meatballs": "impossible-foods",
  "impossible-ground": "impossible-foods",
  "impossible-nuggets": "impossible-foods",
  "impossible-bowls": "impossible-foods",
  "impossible-ready": "impossible-foods",

  // Oatly brands (expanded)
  "oatly": "oatly",
  "oatly-milk": "oatly",
  "oatly-ice-cream": "oatly",
  "oatly-yogurt": "oatly",
  "oatly-cream": "oatly",
  "oatly-spreads": "oatly",
  "oatly-custard": "oatly",
  "oatly-cold-brew": "oatly",
  "oatly-drinks": "oatly",
  "oatly-on-the-go": "oatly",

  // Califia Farms brands (expanded)
  "califia": "califia",
  "califia-farms": "califia",
  "califia-almond-milk": "califia",
  "califia-oat-milk": "califia",
  "califia-coffee": "califia",
  "califia-creamer": "califia",
  "califia-protein": "califia",
  "califia-juice": "califia",
  "califia-barista": "califia",
  "califia-yogurt": "califia",

  // More brands coming in next message...
};

const CANADIAN_PARENT_COMPANIES = {
  // Restaurant/Cafe brands
  "second-cup": "second-cup",
  "tim-hortons": "tim-hortons",
  "swiss-chalet": "recipe-unlimited",
  "harveys": "recipe-unlimited",
  "st-hubert": "recipe-unlimited",
  
  // Grocery/Food brands
  "presidents-choice": "loblaws",
  "no-name": "loblaws",
  "great-value-canada": "loblaws",
  "compliments": "sobeys",
  "selection": "metro",
  "irresistibles": "metro",
  
  // Food Manufacturers
  "maple-leaf-foods": "maple-leaf",
  "schneiders": "maple-leaf",
  "saputo": "saputo",
  "armstrong": "saputo",
  "dairyland": "saputo",
  "neilson": "saputo",
  "baxter": "saputo",
  
  // Beverage Companies
  "cott": "cott",
  "canada-dry-canada": "canada-dry",
  
  // Snack/Confectionery
  "dare-foods": "dare",
  "leclerc": "leclerc",
  "covered-bridge": "covered-bridge",
  "hawkins-cheezies": "hawkins",
}

export function isAmericanBrand(brandName: string): boolean {
  if (!brandName) return false

  // Convert brand name to lowercase and remove special characters
  const normalizedBrand = brandName.toLowerCase().replace(/[^a-z0-9]/g, "")

  // Check if the brand is in our mapping
  return Object.keys(AMERICAN_PARENT_COMPANIES).some((brand) =>
    normalizedBrand.includes(brand.replace(/[^a-z0-9]/g, "")),
  )
}

export function isCanadianBrand(brandName: string): boolean {
  if (!brandName) return false

  // Convert brand name to lowercase and remove special characters
  const normalizedBrand = brandName.toLowerCase().replace(/[^a-z0-9]/g, "")

  // Check if the brand is in our mapping
  return Object.keys(CANADIAN_PARENT_COMPANIES).some((brand) =>
    normalizedBrand.includes(brand.replace(/[^a-z0-9]/g, "")),
  )
}

export function getProductOrigin(product: any): string {
  if (!product.brands) return "Origin unknown"

  // Check for known Canadian brands first
  if (isCanadianBrand(product.brands)) {
    return "Owned by Canada"
  }

  // Then check for known American brands
  if (isAmericanBrand(product.brands)) {
    return "Owned by US"
  }

  // If no brand match, check country tags
  if (product.countries_tags?.includes("en:canada")) {
    return "Made in Canada"
  } else if (product.countries_tags?.includes("en:united-states")) {
    return "Made in US"
  }

  // If no matches found
  return "Not Canadian or American"
}

export function getPrimaryLocation(product: any): string {
  if (!product.countries) return "Location unknown"
  return product.countries.split(",")[0].trim()
}

